### PR TITLE
Improve the wait to avoid interacting with an element before it's ready

### PR DESCRIPTION
**Pull request by davehunt**
The https://github.com/SeleniumHQ/selenium/commit/0eec81da52ba4dfb16de590e6e82ebafa452416f fix in Selenium caused our BIDPOM wait to start failing. We were clicking on elements when they weren't the topmost element, so now the clicks are handled more like they would for a user. I've improved our waits so they handle the loading spinner that flashes up in Persona.

I've also improved the README, updated the requirements, and bumped the version number as we'll need to push this to PyPI.

### CODE REVIEW

**Comment by davehunt** [comment]
Pinging @mozilla/web-qa-sorcerers for review.

**Comment by rbillings** [comment]
LGTM

**Comment by bobsilverberg** [comment]
@davehunt This is different from the change we discussed last week, which would have used an expected condition. Are you confident that this is okay, as it seems different to me. I did test this and it seems to work fine for me. In 15 runs using Se 2.48 the tests passed each time, so r+.

**Comment by davehunt** [comment]
> @davehunt This is different from the change we discussed last week, which would have used an expected condition. Are you confident that this is okay, as it seems different to me. I did test this and it seems to work fine for me. In 15 runs using Se 2.48 the tests passed each time, so r+.

Yep, I bisected Selenium and discovered why this had only recently started failing. I looked again at the changes to the DOM during this time, and this was a much better approach. My previous 'hack' was just my first stab at fixing the problem.

**Comment by bobsilverberg** [comment]
Thanks @davehunt. I believe this is good to go then, so I shall merge it.

**Pull request merged**
